baseURL = "https://ws.0000cd.com/" #ä½ çš„ç½‘å€,ä»¥æ–œæ  / ç»“å°¾
languageCode = "zh-CN"
title = "æ¸¸ä¾ å®¢" #ç½‘ç«™åç§°
theme = "bluf"

[params]
  pagename = "æ¸¸ä¾ å®¢" #é¦–é¡µæ ‡é¢˜
  description = " é²œèŠ±æ€’é©¬å°‘å¹´æ—¶ï¼Œä¸€æ—¥çœ‹å°½é•¿å®‰èŠ±ã€‚" #SEOï¼Œä½ çš„ç½‘ç«™æè¿°
  keywords = [
  "epub",
  "å°è¯´",
  "ç½‘æ–‡",
  "å‡ºç‰ˆä¹¦",
  "æ¨ç†",
  "ç§‘å¹»"
] #SEOï¼Œç½‘ç«™å…³é”®è¯
  author = "æ¸¸ä¾ å®¢" #SEOï¼Œç½‘ç«™ä½œè€…
  alias ="å†è§å°‘å¹´æ‹‰æ»¡å¼“ï¼Œä¸æƒ§å²æœˆä¸æƒ§é£ã€‚" #SEOï¼Œå¯åˆ é™¤
  license="CC BY-NC 4.0" #ç½‘ç«™æˆæƒä¿¡æ¯ï¼Œhttps://chooser-beta.creativecommons.org/

  enableUmami = false #umami ç»Ÿè®¡ç›¸å…³ï¼Œæ²¡æœ‰è¯· falseï¼Œhttps://umami.is/
  UmamiLink = "https://eu.umami.is/script.js"
  UmamiID = "02cc419c-d758-4a4f-a9bd-1e442b1f8435"

  lightColor = "#0000cd" # æµ…è‰²å¼ºè°ƒè‰²ï¼Œæ¨èè¾ƒæ·±
  darkColor = "#fafafa" # æ·±è‰²å¼ºè°ƒè‰²ï¼Œæ¨èè¾ƒæµ…

  gallery = true #å¯ç”¨ç”»å»Šæ¨¡å¼

  greetings = [
    "ä¸å¿å†ä¸–ç›¸é€¢æ—¥ï¼Œç‰æ ‘ä¸´é£ä¸€å°‘å¹´",
    "å°‘å¹´ä¸æƒ§å²æœˆé•¿ï¼Œå½¼æ–¹å°šæœ‰è£å…‰åœ¨",
    "æ–°ä¸°ç¾é…’æ–—ååƒï¼Œå’¸é˜³æ¸¸ä¾ å¤šå°‘å¹´",
    "ç›¸é€¢æ„æ°”ä¸ºå›é¥®ï¼Œç³»é©¬é«˜æ¥¼å‚æŸ³è¾¹",
    "çŠ€æ¸ ç‰å‰‘è‰¯å®¶å­ï¼Œç™½é©¬é‡‘ç¾ä¾ å°‘å¹´",
    "é¡»çŸ¥å°‘å¹´å‡Œäº‘å¿—ï¼Œæ›¾è®¸äººé—´ç¬¬ä¸€æµ",
    "ä½ ç”Ÿæ¥åº”ä¸ºé«˜å±±ï¼Œè€Œéè‰è½",
    "ç¬¬ä¸€æ¬¡é‡è§ä½  åƒå¾®é£ åƒæš–é˜³ åƒå°‘å¥³æ¢¦",
    "å‰‘æœªä½©å¦¥ï¼Œå‡ºé—¨å·²æ˜¯æ±Ÿæ¹–ï¼›åƒå¸†è¿‡å°½ï¼Œå½’æ¥ä»æ˜¯å°‘å¹´",
] #è®¿å®¢éšæœºé—®å€™ï¼Œä¸ºç©ºä¸å¯ç”¨
  mobileGreetings = [
    "æ¨èç”µè„‘è®¿é—®ï¼Œä½“éªŒæ›´ä½³",
] #ç§»åŠ¨ç«¯è®¿å®¢éšæœºé—®å€™ï¼Œä¸ºç©ºä½¿ç”¨ greetings

confettiEmojis = [ 'ğŸ¥Ÿ', 'ğŸœ', 'ğŸŠ', 'ğŸ§§', 'ğŸ§¨', 'ğŸ®', 'ğŸ‰', 'ğŸº' ] # æ¸…é™¤ç­›é€‰æ—¶æ’’èŠ±ï¼Œä¸ºç©ºä¸å¯ç”¨
  

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
  
[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"


[markup]
[markup.highlight]
    style = "gruvbox"

[minify]
  minifyOutput = true
